### PR TITLE
simavr: intital formula

### PR DESCRIPTION
**Pull request by jedahan**
simavr is nice for developing on a plane or in a subway

### CODE REVIEW

**Comment by larsimmisch** [comment]
Thanks for you pull request. simavr looks cool. I'll probably test it later today.

This is totally unrelated to simulavr, right?

**Comment by jedahan** [comment]
very similar, but I had no idea about simulavr, which looks awesome too.

**Comment by larsimmisch** [comment]
I can not compile this:

First, the SHA was wrong:

```
lars@volta /usr/local/Library/Taps/osx-cross/homebrew-avr (jedahan-simavr)$ brew install simavr
==> Installing simavr from osx-cross/homebrew-avr
==> Installing dependencies for osx-cross/avr/simavr: libelf
==> Installing osx-cross/avr/simavr dependency: libelf
==> Downloading https://homebrew.bintray.com/bottles/libelf-0.8.13_1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libelf-0.8.13_1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libelf/0.8.13_1: 11 files, 252K
==> Installing osx-cross/avr/simavr
==> Downloading https://github.com/buserror/simavr/archive/v1.2.tar.gz
==> Downloading from https://codeload.github.com/buserror/simavr/tar.gz/v1.2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c7f645b323d74247409b50ea6915f1f324a7ee2a799ef107613626801defc070
Actual: e9e3b678416faf7f736538d2c0dae63d4f1acd01af59ab4e80822145e3a15971
Archive: /Library/Caches/Homebrew/simavr-1.2.tar.gz
To retry an incomplete download, remove the file above.
```

After fixing this, I got:

```
lars@volta /usr/local/Library/Taps/osx-cross/homebrew-avr (jedahan-simavr)*$ brew install simavr
==> Installing simavr from osx-cross/homebrew-avr
==> Downloading https://github.com/buserror/simavr/archive/v1.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/simavr-1.2.tar.gz
==> make install DESTDIR=/usr/local/Cellar/simavr/1.2 HOMEBREW_PREFIX=/usr/local/Cellar/simavr/1.2 RELEA
Last 15 lines from /Users/lars/Library/Logs/Homebrew/simavr/01.make:
CONF sim_core_decl.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make libsimavr run_avr
fatal: Not a git repository (or any of the parent directories): .git
sim/sim_elf.c:32:10: fatal error: 'libelf.h' file not found
#include <libelf.h>
         ^
1 error generated.
CC sim/sim_cycle_timers.c
make[2]: *** [obj-x86_64-apple-darwin15.0.0/sim_elf.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CC sim/sim_avr.c
CC sim/sim_gdb.c
CC sim/sim_core.c
make[1]: *** [all] Error 2
make: *** [install] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/osx-cross/homebrew-avr/issues
```

I didn't look into this issue closely, but `libelf.h` is installed, in `/usr/local/include/libelf/libelf.h`

I wonder why the offending line does not read:

```
#include <libelf/libelf.h>
```

Care to update the pull request?

**Comment by ladislas** [comment]
Why not create a separate repo for that? It doesn't need to be include with avr-gcc.

**Comment by larsimmisch** [comment]
Hmm. I don't understand that objection. If we accept the pull request, `simavr` would just live in the tap `homebrew-avr` and that seems a logical place to me. A new tap would be overkill, I think.

**Comment by leojrfs** [comment]
Why a separated repo? This one should be the general avr tools stuff... avr-gcc is a formula, in this homebrew-avr repo. 
So in my opinion this avr repo should have all formulas related to avr tools.

**Comment by jedahan** [comment]
@larsimmisch I totally didn't test 1.2, just HEAD. I am sorry for wasting your time because of that. I will work on fixing the build for 1.2.

@ladislas the main reason I submitted **simavr** to homebrew-avr was that it is impossible to do a required `depends_on` for homebrew across taps. See https://github.com/Homebrew/homebrew/pull/46080/files#r45106853 .

**Comment by ladislas** [comment]
you're right, sorry for the objection ;)
